_target_: walrus.trainer.checkpoints.CheckPointer
save_dir: checkpoints/${name}

# load_checkpoint_path is for a sharded checkpoint when a you have a directory containing
# per-rank or per-shard files produced by a distributed (FSDP/HSDP) training run.
# In the backend, load_checkpoint_path is loaded by torch.distributed.checkpoint
# so the checkpoint is created directly across ranks (checkpoints.py:190-246).
load_checkpoint_path: null # <path>/checkpoints/sharded_checkpoint_dir/
coalesced_checkpoint_path: /leonardo_scratch/fast/ICT26_MHPC/sshamsi/walrus_pretrained/walrus.pt # Only specify load_checkpoint_path or coalesced_checkpoint_path - coalesced uses a single checkpoint assumed to be on CPU
save_best: True
checkpoint_frequency: 20
align_fields: True # Whether to align the fields in the checkpoint to the model, useful if there are new fields or the data is loaded in a different order
load_chkpt_after_finetuning_expansion: False # Whether to load the coalesced checkpoint after expanding the model for finetuning. If False, the checkpoint is loaded before expansion.
