sbatch example_run_scripts/grid_search_0.sh
sleep .2
sbatch example_run_scripts/grid_search_1.sh
sleep .2
sbatch example_run_scripts/grid_search_2.sh
sleep .2
sbatch example_run_scripts/grid_search_3.sh
sleep .2
sbatch example_run_scripts/grid_search_4.sh
sleep .2
sbatch example_run_scripts/grid_search_5.sh
sleep .2
sbatch example_run_scripts/grid_search_6.sh
sleep .2
sbatch example_run_scripts/grid_search_7.sh
sleep .2
sbatch example_run_scripts/grid_search_8.sh
sleep .2
sbatch example_run_scripts/grid_search_9.sh
sleep .2
sbatch example_run_scripts/grid_search_10.sh
sleep .2
sbatch example_run_scripts/grid_search_11.sh
sleep .2
sbatch example_run_scripts/grid_search_12.sh
sleep .2
sbatch example_run_scripts/grid_search_13.sh
sleep .2
sbatch example_run_scripts/grid_search_14.sh
sleep .2
sbatch example_run_scripts/grid_search_15.sh
sleep .2
sbatch example_run_scripts/grid_search_16.sh
sleep .2
sbatch example_run_scripts/grid_search_17.sh
sleep .2
sbatch example_run_scripts/grid_search_18.sh
sleep .2
sbatch example_run_scripts/grid_search_19.sh
sleep .2
sbatch example_run_scripts/grid_search_20.sh
sleep .2
sbatch example_run_scripts/grid_search_21.sh
sleep .2
sbatch example_run_scripts/grid_search_22.sh
sleep .2
sbatch example_run_scripts/grid_search_23.sh
sleep .2
sbatch example_run_scripts/grid_search_24.sh
sleep .2
sbatch example_run_scripts/grid_search_25.sh
sleep .2
sbatch example_run_scripts/grid_search_26.sh
sleep .2
sbatch example_run_scripts/grid_search_27.sh
sleep .2
sbatch example_run_scripts/grid_search_28.sh
sleep .2
sbatch example_run_scripts/grid_search_29.sh
sleep .2
sbatch example_run_scripts/grid_search_30.sh
sleep .2
sbatch example_run_scripts/grid_search_31.sh
sleep .2
sbatch example_run_scripts/grid_search_32.sh
sleep .2
sbatch example_run_scripts/grid_search_33.sh
sleep .2
sbatch example_run_scripts/grid_search_34.sh
sleep .2
sbatch example_run_scripts/grid_search_35.sh
sleep .2
sbatch example_run_scripts/grid_search_36.sh
sleep .2
sbatch example_run_scripts/grid_search_37.sh
sleep .2
sbatch example_run_scripts/grid_search_38.sh
sleep .2
sbatch example_run_scripts/grid_search_39.sh
sleep .2
sbatch example_run_scripts/grid_search_40.sh
sleep .2
sbatch example_run_scripts/grid_search_41.sh
sleep .2
sbatch example_run_scripts/grid_search_42.sh
sleep .2
sbatch example_run_scripts/grid_search_43.sh
sleep .2
sbatch example_run_scripts/grid_search_44.sh
sleep .2
sbatch example_run_scripts/grid_search_45.sh
sleep .2
sbatch example_run_scripts/grid_search_46.sh
sleep .2
sbatch example_run_scripts/grid_search_47.sh
sleep .2
sbatch example_run_scripts/grid_search_48.sh
sleep .2
sbatch example_run_scripts/grid_search_49.sh
sleep .2
sbatch example_run_scripts/grid_search_50.sh
sleep .2
sbatch example_run_scripts/grid_search_51.sh
sleep .2
sbatch example_run_scripts/grid_search_52.sh
sleep .2
sbatch example_run_scripts/grid_search_53.sh
sleep .2
sbatch example_run_scripts/grid_search_54.sh
sleep .2
sbatch example_run_scripts/grid_search_55.sh
sleep .2
sbatch example_run_scripts/grid_search_56.sh
sleep .2
sbatch example_run_scripts/grid_search_57.sh
sleep .2
sbatch example_run_scripts/grid_search_58.sh
sleep .2
sbatch example_run_scripts/grid_search_59.sh
sleep .2
sbatch example_run_scripts/grid_search_60.sh
sleep .2
sbatch example_run_scripts/grid_search_61.sh
sleep .2
sbatch example_run_scripts/grid_search_62.sh
sleep .2
sbatch example_run_scripts/grid_search_63.sh
sleep .2